---

- hosts: chongkhorun_app
  become: true
  gather_facts: no
  vars:
   ansible_python_interpreter: "/usr/bin/env python"

  # roles:
  #   - role: nodesource.node

  tasks:
   - name: update apt-get
     raw: sudo apt-get update

   - name: install python 2
     raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
   - name: set timezone to Asia/Bangkok
     timezone:
      name: Asia/Bangkok

   - name: install python pip
     apt: name=python-pip state=present

   - name: add confirm Y in apt-get install
     apt: name=supervisor state=present force=yes

   - name: install supervisor
     apt: name=supervisor state=present

  #  - name: install nodejs
  #    apt: name=nodejs state=present

 # - name: install npm
 #    apt: name=npm state=present

   - name: install unzip
     apt:
       name: unzip
       state: present
      #      mode: 0755
   - name: setup max connection
     sysctl:
      name: net.core.somaxconn
      value: 10000
      state: present
      reload: yes

    ### setup max open file
   - name: setup max open file
     sysctl:
      name: fs.file-max
      value: 500000
      state: present
      reload: yes

# Add or modify nofile soft limit for the user joe
   - name: setup max open file
     pam_limits:
      domain: root
      limit_type: soft
      limit_item: nofile
      value: 500000

# Add or modify nofile soft limit for the user joe
   - name: setup max open file
     pam_limits:
      domain: root
      limit_type: hard
      limit_item: nofile
      value: 500000

  #  - name: install redis
  #    apt:
  #      name: redis-server
  #      state: present

   - name: install mysql
     apt: name=mysql-server state=present
 #  - name: install mysql-python
 #    raw: pip install MySQL-python

   - name: install lib mysql client -dev
     apt: name=libmysqlclient-dev state=present

   - name: install python pip
     apt: name=python-pip state=present
   - name: update pip
     raw: pip install -U pip
   - name: Install the Python MySQLB module
     pip: name=MySQL-python
...
